0   = "Ток инвертора1"
1   = "Ток инвертора2"
2   = "Ток инвертора3"
3   = "Ток инвертора4"
4   = "Ток инвертора5"
5   = "Ток инвертора6"
6   = "Ток инвертора7"
7   = "Ток инвертора8"
8   = "Мягкий стоп(добавлен программно)"
9   = "Общий флаг - аппаратная защита"
10  = "Питание платы управления 5В и 15В"
11  = "Драйверная БИРН3"
12  = "Драйверная БИРН2"
13  = "Драйверная БИРН1"
14  = "Жесткий стоп"
15  = "Драйверная инверторов"
16  = "Дисбаланс тока в канале БИРН1"
17  = "Дисбаланс тока в канале БИРН2"
18  = "Дисбаланс тока в канале БИРН3"
19  = "Ток БИРН превысил ток перегрузки"
20  = "Низкое напряжения на выпрямителе"
21  = "Высокое напряжения на выпрямителе"
22  = "Перегрев"
23  = "Проток"
24  = "Частота минимум"
25  = "Частота максимум"
26  = "Нет сигнала от формирователя ФАПЧ"
27  = "Неверная частота генератора"
28  = "Связь по RS485"
29  = "Неверная конфигурация датчиков"
30  = "Память не обнаружена или не инициализирована"
31  = "Перегрузка инвертора"

