[[pages]]
background = "mimic/background.png"

[pages.pressure]
"sensor.DP1" = [ 200, 28 ] 
"sensor.DP2" = [ 250, 352 ] 
"sensor.DP3" = [ 250, 439 ] 

[pages.temperature]
"sensor.DT1"  = [ 555, 203 ]
"sensor.DT2"  = [ 606, 203 ]
"sensor.DT3"  = [ 657, 203 ]
"sensor.DT4"  = [ 747, 203 ]
"sensor.DT5"  = [ 855, 203 ]
"sensor.DT6"  = [ 420, 202 ]
"sensor.DT7"  = [ 150, 28 ]
"sensor.DT8"  = [ 199, 352 ]
"sensor.DT9"  = [ 205, 188 ]
"sensor.DT10" = [ 280, 188 ]

[pages.inflow]
"sensor.FC1"  = [ 555, 153 ]
"sensor.FC2"  = [ 606, 153 ]
"sensor.FC3"  = [ 657, 153 ]
"sensor.FC4"  = [ 747, 95 ]
"sensor.FC5"  = [ 855, 95 ]
"sensor.FC6"  = [ 420, 97 ]
"sensor.FC9"  = [ 380, 315 ]
"sensor.FC10" = [ 380, 391 ]
"sensor.FC11" = [ 205, 138 ]
"sensor.FC12" = [ 280, 138 ]

[pages.showers]
0 = [ 568, 285 ]
1 = [ 568, 327 ]
2 = [ 541, 360 ]
3 = [ 541, 402 ]
4 = [ 387, 429 ]

[pages.valves]
A1  = [ 229, 78 ]
A13 = [ 286, 427, 4 ]
A14 = [ 417, 303, 0, 1 ]
A15 = [ 417, 379, 2, 3 ]

[pages.flags]
"fc"       = [ 690, 320 ]
"door-0"   = [ 690, 350 ]
"door-1"   = [ 690, 380 ]
"pressure" = [ 690, 410 ]
"bki"      = [ 690, 440 ]

