multiplier = [
    { src = "pr200-A2.dp",      rkey = "mDP-1", k = 0.1 },
    { src = "pr200-A1.dp.0",    rkey = "mDP-2", k = 0.1 },
    { src = "pr200-A1.dp.1",    rkey = "mDP-3", k = 0.1 },
    
    { src = "pr200-A2.dt.0",    rkey = "mDT-1",  k = 0.1 },
    { src = "pr200-A2.dt.1",    rkey = "mDT-2",  k = 0.1 },
    { src = "pr200-A2.dt.2",    rkey = "mDT-3",  k = 0.1 },
    { src = "pr200-A2.dt.3",    rkey = "mDT-4",  k = 0.1 },
    { src = "pr200-A2.dt.4",    rkey = "mDT-5",  k = 0.1 },
    { src = "pr200-A2.dt.5",    rkey = "mDT-6",  k = 0.1 },
    { src = "pr200-A2.dt.6",    rkey = "mDT-7",  k = 0.1 },
    { src = "pr200-A1.dt",      rkey = "mDT-8",  k = 0.1 },
    { src = "pr200.dt.0",       rkey = "mDT-9",  k = 0.1 },
    { src = "pr200.dt.1",       rkey = "mDT-10", k = 0.1 },
    
    { src = "pr200-A2.fc.0",    rkey = "mFC-1",  k = 0.1 },
    { src = "pr200-A2.fc.1",    rkey = "mFC-2",  k = 0.1 },
    { src = "pr200-A2.fc.2",    rkey = "mFC-3",  k = 0.1 },
    { src = "pr200-A2.fc.3",    rkey = "mFC-4",  k = 0.1 },
    { src = "pr200-A2.fc.4",    rkey = "mFC-5",  k = 0.1 },
    { src = "pr200-A2.fc.5",    rkey = "mFC-6",  k = 0.1 },
    { src = "pr200-A1.fc.0",    rkey = "mFC-9",  k = 0.1 },
    { src = "pr200-A1.fc.1",    rkey = "mFC-10", k = 0.1 },
    { src = "pr200.fc.0",       rkey = "mFC-11", k = 0.1 },
    { src = "pr200.fc.1",       rkey = "mFC-12", k = 0.1 },

    { src = "fc.F", rkey = "fc-F", k = 10  },
    { src = "fc.I", rkey = "fc-I", k = 0.1 },
    { src = "fc.P", rkey = "fc-P", k = 100 },
    { src = "fc.U", rkey = "fc-U", k = 1 }
]

getbit = [
    { src = "pr200-A1.vmask", rkey = "valve.A14",   idx = 0 },
    { src = "pr200-A1.vmask", rkey = "valve.A15",   idx = 1 },
    { src = "pr200-A1.vmask", rkey = "valve.A13",   idx = 2 },
    
    { src = "plc-0.bits", rkey = "axis-imove.-A", idx = 7  },
    { src = "plc-0.bits", rkey = "axis-imove.+A", idx = 6  },
    { src = "plc-0.bits", rkey = "axis-imove.-B", idx = 8  },
    { src = "plc-0.bits", rkey = "axis-imove.+B", idx = 9  },
    { src = "plc-0.bits", rkey = "axis-imove.-C", idx = 11 },
    { src = "plc-0.bits", rkey = "axis-imove.+C", idx = 10 },
    { src = "plc-0.bits", rkey = "axis-imove.-U", idx = 12 },
    { src = "plc-0.bits", rkey = "axis-imove.+U", idx = 13 },
    { src = "plc-0.bits", rkey = "axis-imove.-V", idx = 27 },
    { src = "plc-0.bits", rkey = "axis-imove.+V", idx = 28 },
    { src = "plc-0.bits", rkey = "axis-imove.-X", idx = 2  },
    { src = "plc-0.bits", rkey = "axis-imove.+X", idx = 3  },
    { src = "plc-0.bits", rkey = "axis-imove.-Y", idx = 4  },
    { src = "plc-0.bits", rkey = "axis-imove.+Y", idx = 5  },
    { src = "plc-0.bits", rkey = "axis-imove.-Z", idx = 0  },
    { src = "plc-0.bits", rkey = "axis-imove.+Z", idx = 1  },
    { src = "plc-0.bits", rkey = "axis-speed.bit0", idx = 14  },
    { src = "plc-0.bits", rkey = "axis-speed.bit1", idx = 15  },
    { src = "plc-0.bits", rkey = "start.pump",  idx = 18  },
    { src = "plc-0.bits", rkey = "stop.pump",   idx = 19, active = false },
    { src = "plc-0.bits", rkey = "start.Sp-0",  idx = 16  },
    { src = "plc-0.bits", rkey = "stop.Sp-0",   idx = 17, active = false },
    { src = "plc-0.bits", rkey = "start.Sp-1",  idx = 25  },
    { src = "plc-0.bits", rkey = "stop.Sp-1",   idx = 26, active = false },
    { src = "plc-0.bits", rkey = "start.Sp-2",  idx = 29  },
    { src = "plc-0.bits", rkey = "stop.Sp-2",   idx = 30, active = false },
    { src = "plc-0.bits", rkey = "start.fc",    idx = 20  },
    { src = "plc-0.bits", rkey = "stop.fc",     idx = 21, active = false },
    { src = "plc-0.bits", rkey = "mode.auto",   idx = 22 },
    { src = "plc-0.bits", rkey = "mode.rcu",    idx = 23 },

    { src = "mk110-0.bits", rkey = "rcu-axis.6", idx = 0 },
    { src = "mk110-0.bits", rkey = "rcu-axis.5", idx = 1 },
    { src = "mk110-0.bits", rkey = "rcu-axis.4", idx = 2 },
    { src = "mk110-0.bits", rkey = "rcu-axis.Z", idx = 3 },
    { src = "mk110-0.bits", rkey = "rcu-axis.Y", idx = 4 },
    { src = "mk110-0.bits", rkey = "rcu-axis.X", idx = 5 },

    { src = "plc-0.bits",   rkey = "emg-stop",          idx = 24,   active = false },
    { src = "plc-0.bits",   rkey = "sys.bki-lock",      idx = 31,   active = false }, 
    
    { src = "mk110-1.bits", rkey = "start.spump",       idx = 0 },
    { src = "mk110-1.bits", rkey = "stop.spump",        idx = 1,    active = false },
    { src = "mk110-1.bits", rkey = "sys.conductor-0",   idx = 6 },
    { src = "mk110-1.bits", rkey = "sys.conductor-1",   idx = 7 },
    { src = "mk110-1.bits", rkey = "sys.door-0",        idx = 3 },
    { src = "mk110-1.bits", rkey = "sys.door-1",        idx = 4 },
    { src = "mk110-1.bits", rkey = "sys.pressure",      idx = 5 },
]

