[sensor]
DP1  = "mDP-1"
DP2  = "mDP-2"
DP3  = "mDP-3"

DT1  = "mDT-1"
DT2  = "mDT-2"
DT3  = "mDT-3"
DT4  = "mDT-4"
DT5  = "mDT-5"
DT6  = "mDT-6"
DT7  = "mDT-7"
DT8  = "mDT-8"
DT9  = "mDT-9"
DT10 = "mDT-10"

FC1  =  "mFC-1"
FC2  =  "mFC-2"
FC3  =  "mFC-3"
FC4  =  "mFC-4"
FC5  =  "mFC-5"
FC6  =  "mFC-6"
FC9  =  "mFC-9"
FC10 =  "mFC-10"
FC11 =  "mFC-11"
FC12 =  "mFC-12"

[Sp-0]
DP = "mDP-2"
FC = "mFC-9"
V  = "valve.A14"

[Sp-1]
DP = "mDP-2" 
FC = "mFC-10" 
V  = "valve.A15"

[Sp-2]
DP = "mDP-3" 
V  = "valve.A13"

[sys]
emg-stop    = "emg-stop"

[flag]
door-0      = "sys.door-0"
door-1      = "sys.door-1"
pressure    = "sys.pressure" 
fc          = "sys.fc" 
bki         = "bki-lock"

