0   = "Связь по RS485"
1   = "Низкое напряжения на выпрямителе"
2   = "Высокое напряжения на выпрямителе"
3   = "Ток перегрузка"
4   = "Частота"
5   = "Сигнал ФАПЧ"
8   = "Диагональ"
12  = "Драйвер 1"
13  = "Драйвер 2"

16  = "Перегрев"
17  = "Перегрев 2"
18  = "Перегрев 1"
20  = "Внутреняя аппаратная защита"  
21  = "Внутреняя програмная защита"
22  = "Внешняя аппаратная защита"
24  = "Проток"
25  = "Проток 1"
26  = "Проток 2"
28  = "Память не обнаружена"
29  = "Память пуста"
30  = "Память чтение-запись"
31  = "Питание МП"

