[[pages]]
background = "mimic/background.png"

[pages.pressure]
"sensor.DP1" = [ 200, 28 ] 
"sensor.DP2" = [ 250, 352 ] 
"sensor.DP3" = [ 250, 439 ] 

[pages.temperature]
"sensor.DT1"  = [ 555, 203 ]
"sensor.DT2"  = [ 606, 203 ]
"sensor.DT3"  = [ 657, 203 ]
"sensor.DT4"  = [ 747, 203 ]
"sensor.DT5"  = [ 855, 203 ]
"sensor.DT6"  = [ 420, 202 ]
"sensor.DT7"  = [ 150, 28 ]
"sensor.DT8"  = [ 199, 352 ]
"sensor.DT9"  = [ 205, 188 ]
"sensor.DT10" = [ 280, 188 ]

[pages.inflow]
"sensor.FC1"  = [ 555, 153 ]
"sensor.FC2"  = [ 606, 153 ]
"sensor.FC3"  = [ 657, 153 ]
"sensor.FC4"  = [ 747, 95 ]
"sensor.FC5"  = [ 855, 95 ]
"sensor.FC6"  = [ 420, 97 ]
"sensor.FC9"  = [ 380, 315 ]
"sensor.FC10" = [ 380, 391 ]
"sensor.FC11" = [ 205, 138 ]
"sensor.FC12" = [ 280, 138 ]

[pages.showers]
0 = [ 568, 285 ]
1 = [ 568, 327 ]
2 = [ 541, 360 ]
3 = [ 541, 402 ]
4 = [ 387, 429 ]

[pages.valves]
A1.pos      = [ 232, 78 ]
A1.title-placement = "left"
A13.pos     = [ 286, 427 ]
A13.showers = [ 4 ]
A14.pos     = [ 417, 303 ]
A14.showers = [ 0, 1 ]
A15.pos     = [ 417, 379 ]
A15.showers = [ 2, 3 ]

[pages.flags]
"flag.fc"          = [ 690, 320 ]
"flag.door"        = [ 690, 350 ]
"flag.pressure"    = [ 690, 380 ]
"flag.bki"         = [ 690, 410 ]

[[pages]]
background = "mimic/background-1.png"

[pages.pressure]
"sensor.DP4" = [ 656, 44 ] 

[pages.temperature]
"sensor.DT11"  = [ 656, 86  ]
"sensor.DT12"  = [ 443, 133 ]
"sensor.DT14"  = [ 505, 212 ]
"sensor.DT15"  = [ 443, 373 ]
"sensor.DT17"  = [ 465, 452 ]

[pages.inflow]
"sensor.FC13"  = [ 505, 109 ]
"sensor.FC14"  = [ 555, 169 ]
"sensor.FC15"  = [ 505, 349 ]
"sensor.FC16"  = [ 555, 409 ]

[pages.valves]
VA4.pos  = [ 544, 97  ]
VA5.pos  = [ 653, 157 ]
VA6.pos  = [ 570, 337 ]
VA7.pos  = [ 665, 397 ]
VA10.pos = [ 195, 440 ]

[pages.slevels]
P1 = [ 54 , 341 ]
P2 = [ 83 , 341 ]
P3 = [ 112, 341 ]
P4 = [ 286, 104 ]
P5 = [ 286, 160 ]
P6 = [ 286, 345 ]
P7 = [ 286, 397 ]

[pages.heaters]
WH1.pos = [ 500, 436 ]

[pages.pumps]
H2.pos = [ 421, 156 ]
H2.title-placement = "bottom"
H2.mirror-x = true
H3.pos = [ 265, 439 ]
H3.title-placement = "bottom"
H4.pos = [ 421, 396 ]
H4.title-placement = "bottom"
H4.mirror-x = true

[[pages]]
background = "mimic/background-2.png"

[pages.temperature]
"sensor.DT18"  = [ 454, 138 ]
"sensor.DT20"  = [ 454, 231 ]

[pages.inflow]
"sensor.FC17"  = [ 494, 107 ]
"sensor.FC18"  = [ 538, 179 ]

[pages.valves]
VA8.pos  = [ 540, 95 ]
VA9.pos  = [ 625, 167 ]
VA11.pos = [ 162, 219 ]

[pages.slevels]
P8  = [ 274, 98 ]
P9  = [ 274, 168 ]
P10 = [ 187, 327 ]
P11 = [ 187, 371 ]

[pages.heaters]
WH2.pos = [ 488, 215 ]

[pages.pumps]
H7.pos = [ 33, 364 ]
H5.pos = [ 257, 218 ]
H5.title-placement = "bottom"
H6.pos = [ 425, 166 ]
H6.mirror-x = true
H6.title-placement = "bottom"
